# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10

jobs:
  install-node-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run: npm -f install
      - run: npm run test
workflows:
  test_my_app:
    jobs:
      - install-node-and-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - install-node-and-test
          filters:
            branches:
              only: main