# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  install-node-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: npm -f install 
      - run: node --version
      - run: npm run test
workflows:
  test_my_app:
    jobs:
      - install-node-and-test

# workflows:
#   main:
#     jobs:
#       - node/test:
#           version: '16.2'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node